apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parsec

resources:
  - ../../base

patches:
  # Prod: 2 replicas, higher resources, build from production branch
  - target:
      kind: Deployment
      name: parsec
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"

  - target:
      kind: BuildConfig
      name: parsec
    patch: |
      - op: replace
        path: /spec/source/git/ref
        value: production
