apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: parsec
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/rhpds/parsec.git"
      ref: main
    contextDir: "/"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile
      from:
        kind: ImageStreamTag
        name: python-311:latest
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: parsec:latest
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: parsec-webhook-secret
    - type: Generic
      generic:
        secretReference:
          name: parsec-webhook-secret
    - type: ImageChange
