apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: parsec
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/rhpds/parsec.git"
      ref: main
    contextDir: "/"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: parsec:latest
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
