apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parsec

commonLabels:
  app.kubernetes.io/name: parsec
  app.kubernetes.io/part-of: parsec

resources:
  - configmap.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - security/webhook-rolebinding.yaml
  - auth/oauth-rbac.yaml
  - auth/oauth-proxy.yaml
  - auth/oauth-routes.yaml
  - pricing-cronjob.yaml
  - azure-billing-cronjob.yaml
